/* global $ */
let inquirer = require('inquirer')
let enAry = [
  'A Substantial Effort Will Be Required',
  "A Year From Now It Won't Matter",
  'Absolutely Not',
  'Accept A Change To Your Routine',
  'Act As Though It Is Already Real',
  'Adopt An Adventurous Attitude',
  'Allow Yourself To Rest First',
  'Approach Cautiously',
  'Ask Your Father',
  'Ask Your Mother',
  'Assistance Would Make Your Progress A Success',
  'Avoid The First Solution',
  'Be Delightfully Sure Of It',
  'Be More Generous',
  'Be Patient',
  'Be Practical',
  'Bet On It',
  'Better To Wait',
  'Collaboration Will Be The Key',
  'Consider It An Opportunity',
  'Count To 10; Ask Again',
  'Deal With It Later',
  'Definitely',
  'Do It Early',
  "Don't Ask For Any More At This Time",
  "Don't Be Concerned",
  "Don't Be Pressured Into Acting Too Quickly",
  "Don't Be Ridiculous",
  "Don't Bet On It",
  "Don't Doubt It",
  "Don't Forget To Have Fun",
  "Don't Get Caught Up In Your Emotions",
  "Don't Hesitate",
  "Don't Ignore The Obvious",
  "Don't Overdo It",
  "Don't Wait",
  "Don't Waste Your Time",
  'Doubt It',
  'Enjoy The Experience',
  'Expect To Settle',
  'Explore It With Playful Curiosity',
  'Finish Something Else First',
  'Focus On Your Home Life',
  "Follow Someone Else's Lead",
  'Follow The Advice Of Experts',
  'Follow Through On Your Obligations',
  'Follow Through With Your Good Intentions',
  'Gentle Persistence Will Pay Off',
  'Get A Clearer View',
  'Get It In Writing',
  "Give It All You've Got",
  "If It's Done Well; If Not, Don't Do It At All",
  "If You Do As You're Told",
  "If You Don't Resist",
  'Investigate And Then Enjoy It',
  'It Cannot Fail',
  'It Could Be Extraordinary',
  'It Is Certain',
  'It Is Not Significant',
  'It Is Significant',
  "It Is Something You Won't Forget",
  'It Is Sure To Make Things Interesting',
  'It Is Uncertain',
  'It Is Worth The Trouble',
  'It May Already Be A Done Deal',
  'It May Be Difficult But You Will Find Value In It',
  'It Seems Assured',
  'It Will Affect How Others See You',
  'It Will Be A Pleasure',
  'It Will Bring Good Luck',
  'It Will Create A Stir',
  'It Will Remain Unpredictable',
  'It Will Sustain You',
  'It Would Be Better To Focus On Your Work',
  'It Would Be Inadvisable',
  "It'll Cost You",
  "It's A Good Time To Make Plans",
  "It's Gonna Be Great",
  "It's Not Worth A Struggle",
  "It's Time For You To Go",
  'Keep An Open Mind',
  'Keep It To Yourself',
  'Laugh About It',
  'Leave Behind Old Solutions',
  'Let It Go',
  'Listen More Carefully ; Then You Will Know',
  'Make A List Of Why',
  'Make A List Of Why Not',
  'Maybe',
  'Mishaps Are Highly Probable',
  'Move On',
  'Never',
  'No',
  'No Matter What',
  "Not If You're Alone",
  'Now You Can',
  'Only Do It Once',
  'Others Will Depend On Your Choices',
  'Pay Attention To The Details',
  "Perhaps, When You're Older",
  'Prepare For The Unexpected',
  'Press For Closure',
  'Proceed At A More Relaxed Pace',
  'Realize That Too Many Choices Is As Difficult As Too Few',
  'Reconsider Your Approach',
  'Related Issues May Surface',
  'Remain Flexible',
  'Remove Your Own Obstacles',
  'Reprioritize What Is Important',
  'Respect The Rules',
  'Save Your Energy',
  'Seek Out More Options',
  'Setting Priorities Will Be A Necessary Part Of The Process',
  'Settle It Soon',
  'Shift Your Focus',
  'Speak Up About It',
  'Startling Events May Occur As A Result',
  'Take A Chance',
  'Take Charge',
  'Take More Time To Decide',
  'Tell Someone What It Means To You',
  'That Would Be A Waste Of Money',
  "That's Out Of Your Control",
  'The Answer Is In Your Backyard',
  'The Answer May Come To You In Another Language',
  'The Best Solution May Not Be The Obvious One',
  'The Chance Will Not Come Again Soon',
  'The Circumstances Will Change Very Quickly',
  'The Outcome Will Be Positive',
  'The Situation Is Unclear',
  'There Is A Substantial Link To Another Situation',
  'There Is Good Reason To Be Optimistic',
  'There Is No Guarantee',
  'There Will Be Obstacles To Overcome',
  'This Is A Good Time To Make A New Plan',
  'To Ensure The Best Decision, Be Calm',
  'Trust Your Intuition',
  'Trust Your Original Thought',
  'Try A More Unlikely Solution',
  'Unfavorable At This Time',
  'Unquestionably',
  'Upgrade Any Way You Can',
  'Use Your Imagination',
  'Wait',
  'Wait For A Better Offer',
  'Watch And See What Happens',
  'Watch Your Step As You Go',
  'Whatever You Do The Results Will Be Lasting',
  'Yes',
  "Yes,But Don't Force It",
  'You Are Sure To Have Support',
  'You Are Too Close To See',
  'You Could Find Yourself Unable To Compromise',
  "You Don't Really Care",
  'You Know Better Now Than Ever Before',
  'You May Have Opposition',
  'You May Have To Drop Other Things',
  'You Must',
  'You Must Act Now',
  "You Will Find Out Everything You'll Need To Know",
  'You Will Need To Accommodate',
  'You Will Not Be Disappointed',
  "You'll Be Happy You Did",
  "You'll Get The Final Word",
  "You'll Have To Compromise",
  "You'll Have To Make It Up As You Go",
  "You'll Need More Information",
  "You'll Need To Consider Other Ways",
  "You'll Need To Take The Initiative",
  "You'll Regret It",
  'Your Actions Will Improve Thin'
]
let zhAry = [
  '需要付出大量的努力',
  '一年后就没关系了',
  '绝对不是',
  '接受你日常生活的改变',
  '假装它已经是真实的',
  '采取冒险的态度',
  '让自己先休息',
  '小心接近',
  '问你父亲',
  '问你妈妈',
  '帮助会使你的进步取得成功',
  '避免第一个解决方案',
  '确信无疑',
  '更慷慨点',
  '耐心点',
  '实事求是',
  '打赌吧。',
  '最好等一下',
  '合作将是关键',
  '把它当作一个机会',
  '数到10；再问一次',
  '以后再处理',
  '一定地',
  '早点做吧',
  '现在不要再要求了',
  '别担心',
  '别逼得行动太快',
  '别搞笑了',
  '不要赌它',
  '别怀疑',
  '别忘了玩得开心',
  '不要被你的情绪所吸引',
  '不要犹豫',
  '不要忽视显而易见的',
  '别过分了',
  '别等了',
  '别浪费时间',
  '怀疑一下吧',
  '享受体验',
  '希望解决',
  '带着顽皮的好奇心去探索它',
  '先完成别的事情',
  '关注你的家庭生活',
  '听从别人的领导',
  '听从专家的建议',
  '履行你的义务',
  '带着你的善意去做',
  '温和的坚持会有回报的',
  '看得更清楚',
  '把它写下来',
  '全力以赴',
  '如果做得好，就不要做',
  '如果你照别人说的做',
  '如果你不反抗',
  '调查然后享受',
  '它不会失败的',
  '可能很特别',
  '这是肯定的',
  '这不重要',
  '这很重要',
  '你不会忘记的',
  '一定会让事情变得有趣',
  '这是不确定的',
  '值得麻烦的',
  '可能已经成交了',
  '这可能很困难，但你会从中发现价值。',
  '看起来很有把握',
  '它会影响别人对你的看法',
  '很荣幸',
  '它会带来好运的',
  '它会引起轰动',
  '它仍将是不可预测的',
  '它会支持你',
  '最好集中精力工作',
  '这是不可取的',
  '你会为此付出代价的',
  '现在是制定计划的好时机',
  '会很棒的',
  '不值得斗争',
  '你该走了',
  '保持开放的心态',
  '你自己拿着吧',
  '笑吧。',
  '留下旧的解决方案',
  '放手吧。',
  '仔细听，你就会知道',
  '列出原因',
  '列出原因',
  '也许吧',
  '灾难极有可能发生',
  '继续前进',
  '从未',
  '不',
  '不管怎样',
  '如果你一个人的话就不行了',
  '现在你可以了',
  '只做一次',
  '其他人将取决于你的选择',
  '注意细节',
  '也许，当你长大后',
  '为意外做好准备',
  '按下关闭按钮',
  '以更轻松的速度进行',
  '认识到选择太多和选择太少一样困难',
  '重新考虑你的方法',
  '相关问题可能会浮出水面',
  '保持灵活性',
  '消除你自己的障碍',
  '重新排定什么是重要的',
  '遵守规则',
  '节省你的能量',
  '寻找更多选项',
  '确定优先顺序将是该过程的必要组成部分。',
  '尽快解决',
  '转移你的注意力',
  '说出来吧',
  '结果可能会发生令人震惊的事件。',
  '抓住机会',
  '负责',
  '花更多的时间来决定',
  '告诉别人这对你意味着什么',
  '那是浪费钱',
  '那是你无法控制的',
  '答案在你的后院',
  '答案可能会用另一种语言来回答你。',
  '最好的解决办法可能不是显而易见的。',
  '机会不会很快回来',
  '情况会很快改变',
  '结果将是积极的',
  '情况还不清楚',
  '与另一种情况有实质联系',
  '乐观是有充分理由的',
  '没有保证',
  '会有障碍需要克服',
  '现在是制定新计划的好时机',
  '为确保最佳决策，保持冷静',
  '相信你的直觉',
  '相信你最初的想法',
  '尝试一个更不可能的解决方案',
  '此时不利',
  '毫无疑问',
  '以任何方式升级',
  '发挥你的想象力',
  '等待',
  '等待更好的报价',
  '看看会发生什么',
  '走的时候注意脚下',
  '不管你做什么，结果都会持久的。',
  '是的',
  '是的，但不要强迫',
  '你一定会得到支持的',
  '你离得太近看不见',
  '你会发现自己无法妥协',
  '你真的不在乎',
  '你现在比以前更清楚了',
  '你可能有反对意见',
  '你可能得扔掉其他东西',
  '你必须',
  '你现在必须行动',
  '你会发现你需要知道的一切',
  '你需要适应',
  '你不会失望的',
  '你会很高兴的',
  '你会得到最后一句话的',
  '你必须妥协',
  '你得边走边补',
  '你需要更多的信息',
  '你需要考虑其他方法',
  '你需要主动',
  '你会后悔的',
  '你的行动会有所改善'
]
let firstTxt = '您有一个严肃而非娱乐的问题希望被解答?'
let secondTxt = '想着您心中的问题，闭上您的眼睛，保持几秒后，按回车'
let thirdTxt = '确定要开始解答您的疑惑？'
// 主函数
function answerFunc () {
  console.log('\n《解答您的疑惑》')
  let prompt = inquirer.createPromptModule()
  let questions = [
    {
      type: 'confirm',
      name: 'step1',
      default: false,
      message: $.c.c(firstTxt)
    },
    {
      type: 'confirm',
      name: 'step2',
      message: $.c.c(secondTxt),
      when: function (answers) {
        if (!answers.step1) {
          return 0
        }
        return 1
      }
    },
    {
      type: 'confirm',
      name: 'step3',
      message: $.c.c(thirdTxt),
      default: false,
      when: function (answers) {
        if (!answers.step2) {
          return 0
        }
        return 1
      }
    }
  ]
  prompt(questions).then(answers => {
    if (answers.step3) {
      console.log(
        '\n',
        $.c.y('>>  ' + zhAry[$.tools.rnd(0, zhAry.length - 1)]),
        '\n'
      ) // 返回的结果
    }
  })
}

module.exports = {
  answer: answerFunc
}
